run:
  go: "1.22"
linters:
  enable:
    - thelper
    - gofumpt
    - tparallel
    - unconvert
    - unparam
    - revive

linters-settings:
  gofumpt:
    module-path: sektron
# it weirdly fails when running in github actions on interface composition.
issues:
  exclude-files:
    - ui/parameter.go
