name: build

on:
  push:
    branches: [ "main" ]
    tags: ["v*"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Install Alsa headers
      run: sudo apt-get install libasound2-dev
      if: startsWith(matrix.os, 'ubuntu')

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -o bin/sektron

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Sektron_${{ runner.os}}_${{ github.sha }}
        path: bin/
