name: build

on:
  push:
    branches: [ "main" ]
    tags: ["v*"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 1
    steps:
    - uses: actions/checkout@v3

    - name: Install Alsa headers
      run: sudo apt-get install libasound2-dev
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -o bin/${{ matrix.binary }}

    - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sektron_${{ runner.os}}_${{ github.sha }}
          path: bin/${{ matrix.binary }}
