name: build

on:
  push:
    branches: [ "main" ]
    tags: ["v*"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 1
    steps:
    - uses: actions/checkout@v3

    - name: Install Alsa headers
      run: sudo apt-get install libasound2-dev
      if: startsWith(matrix.os, 'ubuntu')

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build linux|mac
      run: go build -o bin/sektron && chmod +x bin/sektron
      if: ${{ !startsWith(matrix.os, 'windows') }}

    # Disable windows for now has I have no way of testing it.
    # - name: Build windows
    #   run: go build -ldflags "-linkmode 'external' -extldflags '-static'" -o bin/sektron.exe
    #   if: startsWith(matrix.os, 'windows')

    - name: Tar.gz files
      run: tar -zcvf sektron_${{ runner.os}}_${{ github.sha }}.tar.gz LICENSE -C bin sektron
      if: ${{ !startsWith(matrix.os, 'windows') }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: sektron_${{ github.sha }}
        path: sektron_${{ runner.os}}_${{ github.sha }}.tar.gz
        if-no-files-found: error

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sektron_${{ github.sha }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: sektron_*.tar.gz